### ISSUE TITLE
get_wsireader doesn't work for .tiff files converted from jp2

### ISSUE THREAD

**Issue by R-J96** [TissueImageAnalytics/tiatoolbox#314] opened 2022-03-08 20:42 UTC
* TIA Toolbox version: 1.0.1
* Python version: 3.7.8
* Operating System: Ubuntu 20.04

### Description

Using `get_wsireader` on a tiff files converted from jp2 errors but using the OpenSlideWSIReader class works. This in turn means classes like SemanticSegmentor that use `get_wsireader` also don't work with this.

### What I Did
Code to reproduce this
```
wsi = get_wsireader(".../file.tiff")
```
results in following error:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/robj/.conda/envs/tiatoolbox/lib/python3.7/site-packages/tiatoolbox/wsicore/wsireader.py", line 2417, in get_wsireader
    return WSIReader.open(input_img)
  File "/home/robj/.conda/envs/tiatoolbox/lib/python3.7/site-packages/tiatoolbox/wsicore/wsireader.py", line 134, in open
    return VirtualWSIReader(input_img, mpp=mpp, power=power)
  File "/home/robj/.conda/envs/tiatoolbox/lib/python3.7/site-packages/tiatoolbox/wsicore/wsireader.py", line 1816, in __init__
    self.img = utils.misc.imread(self.input_path)
  File "/home/robj/.conda/envs/tiatoolbox/lib/python3.7/site-packages/tiatoolbox/utils/misc.py", line 160, in imread
    image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)
cv2.error: OpenCV(4.5.5) /io/opencv/modules/imgproc/src/color.cpp:182: error: (-215:Assertion failed) !_src.empty() in function 'cvtColor'
```

but using
```
wsi = OpenSlideWSIReader(".../file.tiff")
```
on the same file runs absolutely fine.

TIFFWSIReader gives a different error
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/robj/.conda/envs/tiatoolbox/lib/python3.7/site-packages/tiatoolbox/wsicore/wsireader.py", line 2053, in __init__
    raise ValueError("Unsupported TIFF WSI format.")
ValueError: Unsupported TIFF WSI format.
```

**Comment by shaneahmed** [comment] 2022-03-11 16:28
The issue is being fixed in #317 
Just a comment, please use WSIReader.open() as get_wsireader will be depreciated in future release.

**Closed** 2022-04-09 04:05 UTC
Labels: bug, enhancement
